# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hpnizjD2WA5Cse7nkRalqId4T55jd2p5
"""

"""
================================================
Apple Stock Simulator — Extended Edition
Module 1: Real Historical Shock Calibration
Module 2: News Sentiment Analysis
================================================

NEW DEPENDENCIES:
  pip install yfinance numpy pandas matplotlib scipy textblob requests beautifulsoup4

HOW TO RUN:
  python apple_mc_extended.py

WHAT'S NEW:
  - Pulls real AAPL price data around known historical shock events
  - Measures the actual % drop Apple suffered in each case
  - Uses those real numbers to calibrate your Monte Carlo shock size
  - Fetches recent Apple headlines from Google News RSS (free, no API key)
  - Runs sentiment analysis on those headlines using TextBlob
  - Combines sentiment score with calibrated shock to adjust simulation
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import warnings
import requests
from bs4 import BeautifulSoup
from textblob import TextBlob
from datetime import datetime, timedelta
warnings.filterwarnings("ignore")

try:
    import yfinance as yf
except ImportError:
    raise SystemExit("Please run: pip install yfinance")


# ================================================
# SECTION 1: HISTORICAL SHOCK LIBRARY
# Real events, real dates, what actually happened
# ================================================

HISTORICAL_SHOCKS = {
    "COVID Crash (Feb–Mar 2020)": {
        "start": "2020-02-19",
        "end":   "2020-03-23",
        "description": "Global pandemic declared. Supply chains frozen, stores closed.",
        "category": "supply_chain"
    },
    "US-China Tariffs (May 2019)": {
        "start": "2019-05-06",
        "end":   "2019-06-03",
        "description": "Trump raised tariffs to 25% on Chinese goods. Apple heavily exposed.",
        "category": "geopolitical"
    },
    "iPhone Demand Warning (Jan 2019)": {
        "start": "2019-01-02",
        "end":   "2019-01-14",
        "description": "Apple issued rare revenue warning citing weak China iPhone demand.",
        "category": "demand"
    },
    "China Factory Shutdown (Feb 2022)": {
        "start": "2022-02-24",
        "end":   "2022-03-14",
        "description": "Zhengzhou Foxconn lockdowns disrupted iPhone 14 production.",
        "category": "supply_chain"
    },
    "Tariff Shock (Apr 2025)": {
        "start": "2025-04-03",
        "end":   "2025-04-09",
        "description": "Trump announced sweeping tariffs; Apple fell sharply on China exposure fears.",
        "category": "geopolitical"
    },
}


# ================================================
# SECTION 2: FETCH & MEASURE REAL SHOCKS
# ================================================

def measure_historical_shocks(shocks: dict, ticker="AAPL") -> pd.DataFrame:
    """
    For each historical event, downloads AAPL price data
    and measures the actual % change Apple suffered.
    """
    print("\n" + "="*55)
    print("  MODULE 1: HISTORICAL SHOCK CALIBRATION")
    print("="*55)

    results = []
    for name, info in shocks.items():
        try:
            start = pd.to_datetime(info["start"]) - timedelta(days=3)
            end   = pd.to_datetime(info["end"])   + timedelta(days=3)

            data  = yf.download(ticker, start=start, end=end, progress=False)
            if data.empty or len(data) < 2:
                print(f"  [{name}] — no data available, skipping")
                continue

            close      = data["Close"].squeeze()
            price_start = float(close.iloc[0])
            price_end   = float(close.iloc[-1])
            pct_change  = (price_end - price_start) / price_start * 100
            n_days      = len(close)

            results.append({
                "event":       name,
                "category":    info["category"],
                "description": info["description"],
                "date_start":  info["start"],
                "date_end":    info["end"],
                "price_start": round(price_start, 2),
                "price_end":   round(price_end,   2),
                "pct_change":  round(pct_change,  2),
                "n_days":      n_days,
            })

            sign = "+" if pct_change >= 0 else ""
            print(f"  {name}")
            print(f"    ${price_start:.2f} → ${price_end:.2f}  |  {sign}{pct_change:.1f}%  over {n_days} trading days")

        except Exception as e:
            print(f"  [{name}] — error: {e}")

    df = pd.DataFrame(results)
    return df


def calibrate_shock(shock_df: pd.DataFrame, category: str = "supply_chain") -> float:
    """
    Filters historical shocks by category and returns the
    median % change as a calibrated shock value for the simulation.
    """
    subset = shock_df[shock_df["category"] == category]
    if subset.empty:
        print(f"\n  No historical data for category '{category}', using -3% default.")
        return -0.03

    median_shock = subset["pct_change"].median() / 100
    print(f"\n  Calibrated shock for '{category}' events : {median_shock:+.2%}")
    print(f"  (median of {len(subset)} real historical events)")
    return median_shock


# ================================================
# SECTION 3: NEWS SENTIMENT ANALYSIS
# Fetches real Apple headlines, scores them
# ================================================

def fetch_apple_headlines(n=20) -> list[dict]:
    """
    Scrapes Apple news headlines from Google News RSS feed.
    No API key required — completely free.
    Returns a list of dicts with title, source, published date.
    """
    url = "https://news.google.com/rss/search?q=Apple+AAPL+stock&hl=en-US&gl=US&ceid=US:en"
    headers = {"User-Agent": "Mozilla/5.0"}

    try:
        resp = requests.get(url, headers=headers, timeout=10)
        soup = BeautifulSoup(resp.content, "xml")
        items = soup.find_all("item")[:n]

        headlines = []
        for item in items:
            title   = item.find("title").text   if item.find("title")   else ""
            source  = item.find("source").text  if item.find("source")  else "Unknown"
            pubdate = item.find("pubDate").text if item.find("pubDate") else ""
            headlines.append({"title": title, "source": source, "pubdate": pubdate})

        print(f"\n  Fetched {len(headlines)} headlines from Google News")
        return headlines

    except Exception as e:
        print(f"\n  Could not fetch live headlines ({e})")
        print("  Using sample headlines for demonstration...")
        return [
            {"title": "Apple beats earnings expectations with record services revenue", "source": "Reuters", "pubdate": ""},
            {"title": "iPhone demand in China shows signs of recovery analysts say",    "source": "Bloomberg","pubdate": ""},
            {"title": "Apple supplier warns of production delays amid trade tensions",   "source": "FT",       "pubdate": ""},
            {"title": "Apple faces regulatory scrutiny in EU over App Store policies",   "source": "WSJ",      "pubdate": ""},
            {"title": "Analysts raise Apple price target on strong services growth",     "source": "CNBC",     "pubdate": ""},
        ]


def analyse_sentiment(headlines: list[dict]) -> dict:
    """
    Runs TextBlob sentiment analysis on each headline.
    Returns:
      - per-headline scores
      - overall composite score (-1 = very negative, +1 = very positive)
      - a sentiment-adjusted shock modifier
    """
    print("\n" + "="*55)
    print("  MODULE 2: NEWS SENTIMENT ANALYSIS")
    print("="*55)

    scored = []
    for h in headlines:
        blob       = TextBlob(h["title"])
        polarity   = blob.sentiment.polarity      # -1 to +1
        subjectivity = blob.sentiment.subjectivity  # 0 to 1
        scored.append({**h, "polarity": polarity, "subjectivity": subjectivity})

    df = pd.DataFrame(scored)

    composite   = df["polarity"].mean()
    pos_count   = (df["polarity"] > 0.05).sum()
    neg_count   = (df["polarity"] < -0.05).sum()
    neu_count   = len(df) - pos_count - neg_count

    print(f"\n  Headlines analysed : {len(df)}")
    print(f"  Positive           : {pos_count}")
    print(f"  Neutral            : {neu_count}")
    print(f"  Negative           : {neg_count}")
    print(f"  Composite score    : {composite:+.3f}  (-1=very bearish, +1=very bullish)")

    # Map sentiment score to a shock modifier
    # e.g. composite of -0.3 → adds -1.5% extra shock
    sentiment_modifier = composite * 0.05
    print(f"  Sentiment modifier : {sentiment_modifier:+.2%} adjustment to shock\n")

    print("  Top headlines:")
    for _, row in df.nlargest(3, "polarity").iterrows():
        print(f"    [+{row['polarity']:.2f}] {row['title'][:75]}")
    for _, row in df.nsmallest(3, "polarity").iterrows():
        print(f"    [{row['polarity']:.2f}] {row['title'][:75]}")

    return {
        "df":                df,
        "composite":         composite,
        "pos_count":         pos_count,
        "neg_count":         neg_count,
        "neu_count":         neu_count,
        "sentiment_modifier": sentiment_modifier,
    }


# ================================================
# SECTION 4: MONTE CARLO
# ================================================

def run_monte_carlo(S0, annual_drift, annual_vol, shock, n_sims=1000, n_days=252):
    dt = 1 / 252
    Z  = np.random.standard_normal((n_days, n_sims))
    daily_returns = (annual_drift - 0.5 * annual_vol**2) * dt + annual_vol * np.sqrt(dt) * Z
    daily_returns[0] += shock
    log_paths   = np.cumsum(daily_returns, axis=0)
    price_paths = S0 * np.exp(log_paths)
    return np.vstack([np.full(n_sims, S0), price_paths])


# ================================================
# SECTION 5: VISUALISATION — 4 panel dashboard
# ================================================

def plot_dashboard(price_paths, S0, shock_df, sentiment, shock_used):
    # Taller figure + more breathing room between panels
    fig = plt.figure(figsize=(20, 16))
    fig.patch.set_facecolor("#f9f9f9")
    gs  = gridspec.GridSpec(2, 3, figure=fig, hspace=0.55, wspace=0.45)

    ax_sim  = fig.add_subplot(gs[0, :2])
    ax_hist = fig.add_subplot(gs[0, 2])
    ax_dist = fig.add_subplot(gs[1, 0])
    ax_sent = fig.add_subplot(gs[1, 1])
    ax_info = fig.add_subplot(gs[1, 2])

    days  = np.arange(price_paths.shape[0])
    final = price_paths[-1, :]
    p10   = np.percentile(price_paths, 10, axis=1)
    p50   = np.percentile(price_paths, 50, axis=1)
    p90   = np.percentile(price_paths, 90, axis=1)

    # --- Panel 1: Simulation paths ---
    sample = np.random.choice(price_paths.shape[1], 120, replace=False)
    for i in sample:
        c = "#c0392b" if final[i] < p10[-1] else ("#1d9e75" if final[i] > p90[-1] else "#aaaaaa")
        ax_sim.plot(days, price_paths[:, i], alpha=0.07, linewidth=0.6, color=c)

    ax_sim.fill_between(days, p10, p90, alpha=0.12, color="#185fa5")
    ax_sim.plot(days, p50, color="#185fa5", linewidth=2.5, label=f"Median ${p50[-1]:.0f}")
    ax_sim.plot(days, p10, color="#c0392b", linewidth=1.5, linestyle="--", label=f"P10 ${p10[-1]:.0f}")
    ax_sim.plot(days, p90, color="#1d9e75", linewidth=1.5, linestyle="--", label=f"P90 ${p90[-1]:.0f}")
    ax_sim.axhline(S0, color="#555", linewidth=1, linestyle=":", label=f"Start ${S0:.0f}")
    ax_sim.set_title(
        f"Monte Carlo Paths\nCalibrated Shock: {shock_used:+.2%}  |  Sentiment: {sentiment['composite']:+.3f}",
        fontsize=11, pad=10)
    ax_sim.set_xlabel("Trading Days", fontsize=10)
    ax_sim.set_ylabel("Price (USD)", fontsize=10)
    ax_sim.legend(fontsize=9, loc="upper left")
    ax_sim.set_facecolor("white")
    ax_sim.grid(alpha=0.2)

    # --- Panel 2: Historical shocks ---
    # Shorten labels to just the key phrase, put year on a second line
    if not shock_df.empty:
        short_labels = []
        for label in shock_df["event"]:
            # Split at opening bracket or comma to shorten
            parts = label.replace("(", "\n(")
            short_labels.append(parts[:35])

        colors = ["#c0392b" if v < 0 else "#1d9e75" for v in shock_df["pct_change"]]
        y_pos  = np.arange(len(short_labels))
        bars   = ax_hist.barh(y_pos, shock_df["pct_change"],
                              color=colors, alpha=0.8, edgecolor="none", height=0.55)
        ax_hist.axvline(0, color="#333", linewidth=0.8)

        # Put % labels INSIDE the bars to avoid collision
        for bar, val in zip(bars, shock_df["pct_change"]):
            x_pos  = val / 2  # centre of bar
            ax_hist.text(x_pos, bar.get_y() + bar.get_height() / 2,
                         f"{val:+.1f}%", va="center", ha="center",
                         fontsize=8, color="white", fontweight="bold")

        ax_hist.set_yticks(y_pos)
        ax_hist.set_yticklabels(short_labels, fontsize=8, linespacing=1.2)
        ax_hist.set_title("Real Historical AAPL Shocks", fontsize=11, pad=10)
        ax_hist.set_xlabel("% price change during event", fontsize=9)
        ax_hist.set_facecolor("white")
        ax_hist.grid(alpha=0.2, axis="x")
        ax_hist.tick_params(axis="y", pad=4)
        # Give y labels enough room
        ax_hist.set_xlim(left=shock_df["pct_change"].min() * 1.15)

    # --- Panel 3: Final price distribution ---
    counts, edges, patches = ax_dist.hist(final, bins=40, edgecolor="none")
    p10f, p90f = np.percentile(final, 10), np.percentile(final, 90)
    for patch, left in zip(patches, edges[:-1]):
        patch.set_facecolor("#c0392b" if left < p10f else ("#1d9e75" if left > p90f else "#185fa5"))
        patch.set_alpha(0.75)
    ax_dist.axvline(p50[-1], color="#185fa5", linewidth=2,   label=f"Median ${p50[-1]:.0f}")
    ax_dist.axvline(S0,      color="#555",    linewidth=1.5, linestyle=":", label=f"Start ${S0:.0f}")
    ax_dist.set_title("1-Year Final Price Distribution", fontsize=11, pad=10)
    ax_dist.set_xlabel("Stock Price (USD)", fontsize=10)
    ax_dist.set_ylabel("Simulations", fontsize=10)
    ax_dist.legend(fontsize=9)
    ax_dist.set_facecolor("white")
    ax_dist.grid(alpha=0.2)

    # --- Panel 4: Sentiment — show score only, no long labels on y axis ---
    sent_df  = sentiment["df"].sort_values("polarity").reset_index(drop=True)
    s_colors = ["#c0392b" if p < -0.05 else ("#1d9e75" if p > 0.05 else "#aaaaaa")
                for p in sent_df["polarity"]]
    y_pos_s  = np.arange(len(sent_df))

    ax_sent.barh(y_pos_s, sent_df["polarity"], color=s_colors, alpha=0.8,
                 edgecolor="none", height=0.6)
    ax_sent.axvline(0, color="#333", linewidth=0.8)

    # Short truncated labels on y axis
    ax_sent.set_yticks(y_pos_s)
    ax_sent.set_yticklabels([t[:30] + "…" if len(t) > 30 else t
                              for t in sent_df["title"]], fontsize=7)

    # Score annotations to the right of each bar
    for idx, (_, row) in enumerate(sent_df.iterrows()):
        ax_sent.text(row["polarity"] + 0.01 if row["polarity"] >= 0 else row["polarity"] - 0.01,
                     idx, f"{row['polarity']:+.2f}",
                     va="center", ha="left" if row["polarity"] >= 0 else "right",
                     fontsize=7, color="#333")

    ax_sent.set_title(f"Headline Sentiment\nComposite: {sentiment['composite']:+.3f}", fontsize=11, pad=10)
    ax_sent.set_xlabel("Polarity score", fontsize=10)
    ax_sent.set_facecolor("white")
    ax_sent.grid(alpha=0.2, axis="x")
    # Give labels room on the left
    ax_sent.set_xlim(left=-1.0, right=1.0)

    # --- Panel 5: Summary text ---
    ax_info.axis("off")
    prob_gain = np.mean(final > S0) * 100
    prob_10dn = np.mean(final < S0 * 0.9) * 100

    summary = (
        f"SIMULATION SUMMARY\n"
        f"{'─'*26}\n"
        f"Start price   ${S0:.2f}\n"
        f"Median (P50)  ${np.percentile(final,50):.2f}\n"
        f"Bull (P90)    ${np.percentile(final,90):.2f}\n"
        f"Bear (P10)    ${np.percentile(final,10):.2f}\n"
        f"Best  (P99)   ${np.percentile(final,99):.2f}\n"
        f"Worst (P1)    ${np.percentile(final, 1):.2f}\n"
        f"{'─'*26}\n"
        f"Prob of gain  {prob_gain:.1f}%\n"
        f"Prob >10% dn  {prob_10dn:.1f}%\n"
        f"{'─'*26}\n"
        f"Shock used    {shock_used:+.2%}\n"
        f"Sentiment     {sentiment['composite']:+.3f}\n"
        f"  Positive    {sentiment['pos_count']} headlines\n"
        f"  Neutral     {sentiment['neu_count']} headlines\n"
        f"  Negative    {sentiment['neg_count']} headlines\n"
    )
    ax_info.text(0.05, 0.95, summary, transform=ax_info.transAxes,
                 fontsize=9.5, verticalalignment="top", fontfamily="monospace",
                 bbox=dict(boxstyle="round,pad=0.6", facecolor="white", edgecolor="#ccc"))

    plt.suptitle("Apple Supply Chain Shock Simulator — Extended Edition\n"
                 "Calibrated from Real Historical Events + Live News Sentiment",
                 fontsize=14, fontweight="bold", y=1.01)

    plt.savefig("apple_mc_extended_results.png", dpi=150, bbox_inches="tight",
                facecolor=fig.get_facecolor())
    print("\nChart saved: apple_mc_extended_results.png")
    plt.show()


# ================================================
# SECTION 6: MAIN
# ================================================

def main():
    print("\n" + "="*55)
    print("  APPLE SUPPLY CHAIN SHOCK SIMULATOR — EXTENDED")
    print("="*55)

    np.random.seed(42)

    # --- Fetch Apple baseline ---
    print("\nFetching AAPL market data...")
    data = yf.download("AAPL", period="2y", progress=False)
    close = data["Close"].squeeze()
    S0    = float(close.iloc[-1])
    log_r = np.log(close / close.shift(1)).dropna()
    vol   = float(log_r.std()   * np.sqrt(252))
    drift = float(log_r.mean()  * 252)
    print(f"  Current price : ${S0:.2f}")
    print(f"  Volatility    : {vol:.1%}")
    print(f"  Drift         : {drift:.1%}")

    # --- Module 1: Historical shock calibration ---
    shock_df         = measure_historical_shocks(HISTORICAL_SHOCKS)
    calibrated_shock = calibrate_shock(shock_df, category="supply_chain")

    # --- Module 2: Sentiment analysis ---
    headlines = fetch_apple_headlines(n=20)
    sentiment = analyse_sentiment(headlines)

    # --- Combine: calibrated shock + sentiment modifier ---
    final_shock = calibrated_shock + sentiment["sentiment_modifier"]
    print(f"\n  Final combined shock : {calibrated_shock:+.2%} (historical) "
          f"+ {sentiment['sentiment_modifier']:+.2%} (sentiment) = {final_shock:+.2%}")

    # --- Run Monte Carlo ---
    print(f"\nRunning 1,000 simulations...")
    paths = run_monte_carlo(S0, drift, vol, final_shock, n_sims=1000, n_days=252)
    print("Done.")

    # --- Plot ---
    plot_dashboard(paths, S0, shock_df, sentiment, final_shock)


if __name__ == "__main__":
    main()